import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import '../global-styles/styles.scss';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500", "600", "700"] })

export const metadata: Metadata = {
  title: 'Lalit | Portfolio Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className} flex flex-col h-screen`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
